
-- Security Filter Metadata --

create table security_filter_metadata (
                                         id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
                                         ant_pattern VARCHAR(1024) NOT NULL unique,
                                         expression  VARCHAR(1024) NOT NULL,
                                         sort_order  INTEGER NOT NULL,
                                         PRIMARY KEY (id)
);

-- the end --
