-- ref. Appendix A of Spring Security manual

-- chapter04.01
-- The default appUsers schema of Spring Security

-- USERS Schema
CREATE TABLE appUsers (
                          id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                          email VARCHAR(50) NOT NULL UNIQUE,
                          password VARCHAR(100) NOT NULL,
                          first_name VARCHAR(50) NOT NULL,
                          last_name VARCHAR(50) NOT NULL,
                          PRIMARY KEY (id)
);

-- Events Schema
CREATE TABLE events (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                        event_date TIMESTAMP NOT NULL,
                        summary VARCHAR(50) NOT NULL,
                        description VARCHAR(100) NOT NULL,
                        owner BIGINT NOT NULL,
                        attendee BIGINT NOT NULL,
                        PRIMARY KEY (id),
                        FOREIGN KEY(owner) REFERENCES appUsers(id),
                        FOREIGN KEY(attendee) REFERENCES appUsers(id)
);

-- The End...
